# Replaces the Version constant in ./core/version/version.go with $SPRINT_VERSION
cat > ./core/internal/version/version.go << EOM
package version

// This file is generated by update_version.sh. Do not edit manually.
const Version string = "$SPRINT_VERSION"
const BuildDate string = "$(date +'%Y%m%d-%H%M%S')"
const FullVersion string = Version + "." + BuildDate
EOM
