# Validate that $SPRING_VERSION conforms to the required pattern (e.g. 1.234.5), otherwise exit.
echo $SPRINT_VERSION | grep -Pq '^\d+\.\d+\.\d+$' && \
    echo "Sprint version is valid." || \
    { echo "Sprint version does not match expected pattern."; exit 1; }

# Replaces the Version constant in ./core/version/version.go with $SPRINT_VERSION
cat > ./core/internal/version/version.go << EOM
package version

// This file is generated by update_version.sh. Do not edit manually.
const Version string = "$SPRINT_VERSION"
const BuildDate string = "$(date +'%Y%m%d-%H%M%S')"
const FullVersion string = Version + "." + BuildDate
EOM
