# Validate that $SPRINT_VERSION_WITH_PATCH conforms to the required pattern (e.g. 1.234.5), otherwise exit.
echo $SPRINT_VERSION_WITH_PATCH | grep -Pq '^\d+\.\d+\.\d+$' && \
    echo "Sprint version is valid." || \
    { echo "Sprint version does not match expected pattern."; exit 1; }

NOW=date
BUILD_DATE=$($NOW '+%Y.%m.%d %H:%M:%S')
VERSION_TIMESTAMP=$($NOW '+%Y%m%d-%H%M%S')

# Replaces the Version constant in ./core/version/version.go with $SPRINT_VERSION_WITH_PATCH
cat > ./core/internal/version/version.go << EOM
package version

// This file is generated by update_version.sh. Do not edit manually.
const Version string = "$SPRINT_VERSION_WITH_PATCH"
const VersionTimestamp string = "$VERSION_TIMESTAMP"
const FullVersion string = Version + "." + VersionTimestamp
const BuildDate string = "$BUILD_DATE"
EOM
