// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: dynatrace/odin/proto/collector/metrics/v1/dt_metric_export.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This message is sent from Agent to ActiveGate which, in turn, forwards the message
// to Cluster upon validation of the tenantUUID field.
// This message is sent by an ODIN agent via an HTTP POST request to the AG endpoint "/odin/v1/metrics"
// using Content-Type "application/x-dt-metric-export". The AG will then wrap a `MetricExport` message
// into a com.compuware.apm.protocols.messagedispatching.MessageProtocol.Message to send it to Cluster.
type MetricExport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UUID of the tenant to which the metric data belongs.
	// Everyone that handles these envelopes MUST check that the sender is
	// authorized to submit data for that tenant.
	TenantUUID string `protobuf:"bytes,1,opt,name=tenantUUID,proto3" json:"tenantUUID,omitempty"`
	// The unique ID of the ODIN agent that originally produced this message.
	AgentId int64 `protobuf:"varint,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	// Serialized dynatrace.odin.proto.collector.common.v1.ExportMetaInfo message.
	ExportMetaInfo []byte `protobuf:"bytes,3,opt,name=exportMetaInfo,proto3" json:"exportMetaInfo,omitempty"`
	// Serialized dynatrace.odin.proto.resource.v1.Resource message.
	Resource []byte `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	// Serialized dynatrace.odin.proto.collector.metrics.v1.MINTPayload message.
	MetricData []byte `protobuf:"bytes,5,opt,name=metricData,proto3" json:"metricData,omitempty"`
}

func (x *MetricExport) Reset() {
	*x = MetricExport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricExport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricExport) ProtoMessage() {}

func (x *MetricExport) ProtoReflect() protoreflect.Message {
	mi := &file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricExport.ProtoReflect.Descriptor instead.
func (*MetricExport) Descriptor() ([]byte, []int) {
	return file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDescGZIP(), []int{0}
}

func (x *MetricExport) GetTenantUUID() string {
	if x != nil {
		return x.TenantUUID
	}
	return ""
}

func (x *MetricExport) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *MetricExport) GetExportMetaInfo() []byte {
	if x != nil {
		return x.ExportMetaInfo
	}
	return nil
}

func (x *MetricExport) GetResource() []byte {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *MetricExport) GetMetricData() []byte {
	if x != nil {
		return x.MetricData
	}
	return nil
}

type MINTPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An array of strings, each representing a metric data point
	// using the MINT Line protocol.
	MetricLine []string `protobuf:"bytes,1,rep,name=metricLine,proto3" json:"metricLine,omitempty"`
}

func (x *MINTPayload) Reset() {
	*x = MINTPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MINTPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MINTPayload) ProtoMessage() {}

func (x *MINTPayload) ProtoReflect() protoreflect.Message {
	mi := &file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MINTPayload.ProtoReflect.Descriptor instead.
func (*MINTPayload) Descriptor() ([]byte, []int) {
	return file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDescGZIP(), []int{1}
}

func (x *MINTPayload) GetMetricLine() []string {
	if x != nil {
		return x.MetricLine
	}
	return nil
}

var File_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto protoreflect.FileDescriptor

var file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDesc = []byte{
	0x0a, 0x40, 0x64, 0x79, 0x6e, 0x61, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2f, 0x6f, 0x64, 0x69, 0x6e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x74, 0x5f, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x29, 0x64, 0x79, 0x6e, 0x61, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x6f, 0x64,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x22, 0xac, 0x01,
	0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x55, 0x55, 0x49, 0x44, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0e, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2d, 0x0a, 0x0b,
	0x4d, 0x49, 0x4e, 0x54, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x69, 0x6e, 0x65, 0x42, 0xa1, 0x01, 0x0a, 0x2d,
	0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x6f, 0x64,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x0e, 0x44,
	0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x5a, 0x60, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x79, 0x6e, 0x61, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x2d, 0x6f, 0x73, 0x73, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x74, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x2d, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2d, 0x67,
	0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x6f, 0x64, 0x69, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDescOnce sync.Once
	file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDescData = file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDesc
)

func file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDescGZIP() []byte {
	file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDescOnce.Do(func() {
		file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDescData = protoimpl.X.CompressGZIP(file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDescData)
	})
	return file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDescData
}

var file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_goTypes = []interface{}{
	(*MetricExport)(nil), // 0: dynatrace.odin.proto.collector.metrics.v1.MetricExport
	(*MINTPayload)(nil),  // 1: dynatrace.odin.proto.collector.metrics.v1.MINTPayload
}
var file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_init() }
func file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_init() {
	if File_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricExport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MINTPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_goTypes,
		DependencyIndexes: file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_depIdxs,
		MessageInfos:      file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_msgTypes,
	}.Build()
	File_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto = out.File
	file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_rawDesc = nil
	file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_goTypes = nil
	file_dynatrace_odin_proto_collector_metrics_v1_dt_metric_export_proto_depIdxs = nil
}
