package version

// This file is generated by update_version.sh. Do not edit manually.
const Version string = "0.0.0"
const VersionTimestamp string = "20201122-091244"
const FullVersion string = Version + "." + VersionTimestamp
const BuildDate string = "2020.11.22 09:12:44"
