package version

// This file is generated by update_version.sh. Do not edit manually.
const Version string = "1.251.1"
const VersionTimestamp string = "20221011-124537"
const FullVersion string = Version + "." + VersionTimestamp
const BuildDate string = "2022.10.11 12:45:37"
