package version

// This file is generated by update_version.sh. Do not edit manually.
const Version string = "1.267.1"
const VersionTimestamp string = "20230517-095026"
const FullVersion string = Version + "." + VersionTimestamp
const BuildDate string = "2023.05.17 09:50:26"
