name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint core module
        uses: golangci/golangci-lint-action@v3.2
        with:
          working-directory: core
          args: --verbose

      - name: Lint samples module
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          working-directory: samples
          args: --verbose

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Build core module
        working-directory: core
        run: go build -v ./...

      - name: Build samples module
        working-directory: samples
        run: go build -v ./...

      - name: Test
        run: cd core && go test -v ./...

